/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recursos;

/**
 *
 * @author Leonardo
 */
public class InterfazAyuda extends javax.swing.JDialog {

    /**
     * Creates new form InterfazAyuda
     */
    public InterfazAyuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        todoElemento = new javax.swing.JPanel();
        scrollPanelAyuda = new javax.swing.JScrollPane();
        listaDeAyuda = new javax.swing.JList<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        todoElemento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaDeAyuda.setBackground(new java.awt.Color(0, 0, 0));
        listaDeAyuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        listaDeAyuda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listaDeAyuda.setForeground(new java.awt.Color(204, 255, 255));
        listaDeAyuda.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "*************¿COMO USAR CALCULADORA DE SUBNETTING?************", " ", "- PASO 1:", "Ingrese la direccion ip octeto por octeto en cada campo vacio", " ", "- PASO 2: ", "Seleccione la clase que pertenece a la direccion ip que usted ingreso", "Nota: Tiene un panel en el lado derecho superior que le ayudara a determinar", "de manera simple la clase de su direccion ip (rangos pertenecen al primer octeto)", " ", "- PASO 3:", "Seleccione un prefijo de red segun su preferencia, esto se limita en base a la ", "clase que usted eligio, es decir:", "Clase A ---> Prefijo de Red: 8 hasta 32", "Clase B ---> Prefijo de Red: 16 hasta 32", "Clase C ---> Prefijo de Red: 24 hasta 32", " ", "- PASO 4:", "Seleccione la cantidad de subredes que usted desea generar segun el prefijo ", "de red que usted eligió, por ejemplo:", "Prefijo de Red: 11 ---> Se despliega la cantidad de subredes disponibles ", "en base al prefijo 11", " ", "- PASO 5:", "Presione el boton \"Generar\" para generar la informacion mas importante  de la", "red y de las subredes", " ", "- PASO 6:", "Usted podrá visualizar lo siguiente:", "Informacion de la Red:", "-> Direccion Ip en Binario", "-> Direccion de Red en Decimal", "-> Direccion de Red en Binario", "-> Primera Ip Utilizable", "-> Ultima Ip Utilizable", "-> Broadcast en Decimal", "-> Broadcast en Binario", "-> Mascara de Red en Decimal", "-> Mascara de Red en Binario", "-> Clase a la que pertenece la direccion Ip que se ingresó", "Informacion de cada subred:", "-> Mascara de Subred en Decimal", "-> Mascara de Subred en Binario", "-> Host disponibles por cada Subred", "-> Salto de red, es decir, el incremento de cada subred y en que octeto", "se realiza dicho salto", " ", "PASO 7: ", "Presione el boton \"Elliminar\" en caso que usted desee resetear la calculadora ", "para volver a utilizarla " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaDeAyuda.setToolTipText("");
        scrollPanelAyuda.setViewportView(listaDeAyuda);

        todoElemento.add(scrollPanelAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 480, 330));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoCalcIp.jpg"))); // NOI18N
        todoElemento.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(todoElemento, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(todoElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazAyuda dialog = new InterfazAyuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JList<String> listaDeAyuda;
    private javax.swing.JScrollPane scrollPanelAyuda;
    private javax.swing.JPanel todoElemento;
    // End of variables declaration//GEN-END:variables
}
